name: Common Project Setup
description: Setup Python, install uv, and install dependencies
inputs:
  python-version:
    required: false
    default: '3.10'
  uv-version:
    required: false
    default: '0.7.14'
runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: ${{ inputs.uv-version }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install the project
      run: uv sync --all-packages --locked 